### ISSUE TITLE
Stupid stack

### ISSUE THREAD

**Issue by SaveliyKolesnikov** [AndrewRublyov/RsaChat#1]
Rewrite to use F#, please

**Comment by SaveliyKolesnikov** [comment]
@AndrewRublyov could you please take a look at this? 😜

**Comment by SaveliyKolesnikov** [comment]
@AndrewRublyov

**Comment by seclerp** [comment]
@SaveliyKolesnikov, sorry about that, but I'm not planning to rewrite whole project to F#

You could accomplish it by yourself and send PR 😉
